### ISSUE TITLE
前端！！！！

### ISSUE THREAD

**Issue by samsam2310** [TaiwanCoderLeague/official-site#25]

**Comment by billkunghappy** [comment]
要打甚麼??

**Comment by samsam2310** [comment]
我陸續增加了一些東西
但是我懶得搞前端 
因為真的太難用了
所以你看一看  
有很醜的地方就試著把他修掉
有些地方的使用者介面也可以設計一下

加油！！！

**Comment by billkunghappy** [comment]
ok

**Comment by billkunghappy** [comment]
為什麼login的facebook按鈕樣式明明有從fontawsome引進卻跑不出來??還有頁面的滑動效果消失了
